import { relations } from "drizzle-orm"
import type { AnyPgColumn } from "drizzle-orm/pg-core"
import {
  boolean,
  customType,
  date,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core"

/** Raw bytes, stored and read back as a Node `Buffer` — the PDF's own body. */
const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return "bytea"
  },
})

/* -------------------------------------------------------------------------- */
/*  Auth — the shape better-auth expects. Generated by `@better-auth/cli`.     */
/* -------------------------------------------------------------------------- */

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  /** The public handle: what other learners see, so the email stays private. */
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
})

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
)

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    /** Hashed by better-auth (scrypt); never read by application code. */
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
)

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
)

/* -------------------------------------------------------------------------- */
/*  Spaces & folders — the subject a course belongs to, and how it's filed.    */
/* -------------------------------------------------------------------------- */

/**
 * A top-level subject (a language, or anything else worth its own catalogue).
 * `slug` gives it a stable, readable root URL independent of the title.
 */
export const spaces = pgTable("spaces", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  ownerId: text("owner_id").references(() => user.id, { onDelete: "set null" }),
  /** A palette key (see `lib/colors.ts`), or `null` for the neutral default. */
  color: text("color"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
})

/**
 * The cover banner shown atop a space's card, one per space — a re-upload
 * replaces it outright, same as `courseSheets`.
 */
export const spaceBanners = pgTable("space_banners", {
  spaceId: uuid("space_id")
    .primaryKey()
    .references(() => spaces.id, { onDelete: "cascade" }),
  data: bytea("data").notNull(),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
})

/**
 * A folder inside a space, nestable to any depth via `parentId`. `null`
 * parent means the folder sits at the space's root. Deletion is blocked
 * app-side while a folder still holds anything — `restrict` here is a
 * backstop, not the mechanism.
 */
export const folders = pgTable(
  "folders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    spaceId: uuid("space_id")
      .notNull()
      .references(() => spaces.id, { onDelete: "cascade" }),
    parentId: uuid("parent_id").references((): AnyPgColumn => folders.id, {
      onDelete: "restrict",
    }),
    title: text("title").notNull(),
    /** Rank among siblings. */
    position: integer("position").notNull().default(0),
    /** A palette key (see `lib/colors.ts`), or `null` for the neutral default. */
    color: text("color"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("folders_space_parent_idx").on(
      table.spaceId,
      table.parentId,
      table.position
    ),
  ]
)

/** The cover banner shown atop a folder's card, one per folder. */
export const folderBanners = pgTable("folder_banners", {
  folderId: uuid("folder_id")
    .primaryKey()
    .references(() => folders.id, { onDelete: "cascade" }),
  data: bytea("data").notNull(),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
})

/* -------------------------------------------------------------------------- */
/*  Lessons                                                                    */
/* -------------------------------------------------------------------------- */

export const courses = pgTable("courses", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  /** Date of the lesson, distinct from `createdAt` (notes are typed up later). */
  date: date("date").notNull(),
  /** The subject this course files under. */
  spaceId: uuid("space_id")
    .notNull()
    .references(() => spaces.id, { onDelete: "cascade" }),
  /** `null` means the course sits at the space's root, not inside a folder. */
  folderId: uuid("folder_id").references(() => folders.id, {
    onDelete: "set null",
  }),
  /**
   * BCP-47 locale for pronunciation (e.g. `ko-KR`). `null` means the course
   * carries no spoken-language content, so no TTS UI is shown for it.
   */
  speechLocale: text("speech_locale"),
  /**
   * The author. A course outlives its author's account only if we say so —
   * `set null` keeps the lesson readable, with no one able to edit it.
   */
  ownerId: text("owner_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
})

export const cards = pgTable(
  "cards",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    front: text("front").notNull(),
    /** A generic pronunciation/reading hint — romanization, IPA, anything. */
    phonetic: text("phonetic").notNull().default(""),
    back: text("back").notNull().default(""),
    note: text("note"),
    /** Text alignment for both faces' text. `null` means the default: centered. */
    align: text("align", { enum: ["left", "center", "right", "justify"] }),
    /** Rank in the lesson: the note's own order is meaningful. */
    position: integer("position").notNull(),
  },
  (table) => [index("cards_course_idx").on(table.courseId, table.position)]
)

/**
 * An optional image on one face of a card, keyed by side so front and back
 * are independent — a card can carry neither, either, or both. Mirrors the
 * `courseSheets` blob pattern: bytes live outside `cards` so bulk reads of
 * the deck never carry image data.
 */
export const cardImages = pgTable(
  "card_images",
  {
    cardId: uuid("card_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    side: text("side", { enum: ["front", "back"] }).notNull(),
    data: bytea("data").notNull(),
    contentType: text("content_type").notNull(),
    size: integer("size").notNull(),
    uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.cardId, table.side] })]
)

/**
 * The revision sheet: a designed PDF built offline (see the `course-sheet`
 * skill) from the lesson's words, then uploaded here. One per lesson — a
 * re-upload replaces it outright, since no history of past sheets is worth
 * keeping.
 */
export const courseSheets = pgTable("course_sheets", {
  courseId: uuid("course_id")
    .primaryKey()
    .references(() => courses.id, { onDelete: "cascade" }),
  filename: text("filename").notNull(),
  data: bytea("data").notNull(),
  size: integer("size").notNull(),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
})

/** Write access granted by the owner. Read access needs no row: it is public. */
export const courseEditors = pgTable(
  "course_editors",
  {
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.courseId, table.userId] })]
)

/** A learner's bookmark on a lesson. Private: nobody sees anyone's shortlist. */
export const courseFavorites = pgTable(
  "course_favorites",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.courseId] }),
    index("course_favorites_user_idx").on(table.userId, table.createdAt),
  ]
)

/* -------------------------------------------------------------------------- */
/*  Progress — per learner, never shared                                       */
/*                                                                            */
/*  With one exception, below: having finished a lesson is public. It is the   */
/*  only fact about a learner's progress that leaves their account, and it is  */
/*  a fact alone — never the tallies, the streaks or the series behind it.     */
/* -------------------------------------------------------------------------- */

/**
 * The learner acquired every word of the lesson, once. Written the moment it
 * happens and never taken back: a word sent to review afterwards — or a word
 * added to the lesson later — lowers the bar again, but what was learnt was
 * learnt. Without that, an author adding a word would revoke everyone's
 * success at a stroke.
 */
export const courseCompletions = pgTable(
  "course_completions",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    completedAt: timestamp("completed_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.courseId] }),
    index("course_completions_course_idx").on(
      table.courseId,
      table.completedAt
    ),
  ]
)

/**
 * How a learner stands on one word: `streak` counts the series answered right
 * in a row. `0` means the last answer was a miss — the word is due for review;
 * `KNOWN_STREAK` or more means acquired. A word never answered has no row.
 *
 * `hits` and `misses` are the lifetime tallies behind them. They live here
 * rather than being counted from `run_words` because that history is capped
 * and the learner may erase it — the counters have to outlive it.
 */
export const wordProgress = pgTable(
  "word_progress",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    wordId: uuid("word_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    streak: integer("streak").notNull().default(0),
    /** Times answered right, all series merged. */
    hits: integer("hits").notNull().default(0),
    /** Times the word landed in "à revoir", by a miss or by hand. */
    misses: integer("misses").notNull().default(0),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.wordId] }),
    index("word_progress_course_idx").on(table.userId, table.courseId),
  ]
)

/** One series, complete or cut short. Free practice is never written here. */
export const runs = pgTable(
  "runs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    /** Cards the deck held — larger than the answers when it was cut short. */
    size: integer("size").notNull(),
    /** `false` when the learner closed the series before the last card. */
    completed: boolean("completed").notNull().default(true),
    /** The face that was shown first, kept so a recap can be read in context. */
    frontSide: text("front_side").notNull().default("front"),
    finishedAt: timestamp("finished_at").defaultNow().notNull(),
  },
  (table) => [index("runs_course_idx").on(table.userId, table.courseId)]
)

/** One answered card of a series — what makes the recap possible. */
export const runWords = pgTable(
  "run_words",
  {
    runId: uuid("run_id")
      .notNull()
      .references(() => runs.id, { onDelete: "cascade" }),
    wordId: uuid("word_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    /** `true` for "acquis", `false` for "à revoir". */
    known: boolean("known").notNull(),
    /** Rank in the deck, so the recap lists the words as they came up. */
    position: integer("position").notNull(),
  },
  (table) => [primaryKey({ columns: [table.runId, table.wordId] })]
)

/* -------------------------------------------------------------------------- */

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}))

export const spacesRelations = relations(spaces, ({ many, one }) => ({
  folders: many(folders),
  courses: many(courses),
  owner: one(user, { fields: [spaces.ownerId], references: [user.id] }),
}))

export const foldersRelations = relations(folders, ({ many, one }) => ({
  space: one(spaces, { fields: [folders.spaceId], references: [spaces.id] }),
  parent: one(folders, {
    fields: [folders.parentId],
    references: [folders.id],
    relationName: "folderParent",
  }),
  children: many(folders, { relationName: "folderParent" }),
  courses: many(courses),
}))

export const coursesRelations = relations(courses, ({ many, one }) => ({
  cards: many(cards),
  editors: many(courseEditors),
  favorites: many(courseFavorites),
  completions: many(courseCompletions),
  owner: one(user, { fields: [courses.ownerId], references: [user.id] }),
  space: one(spaces, { fields: [courses.spaceId], references: [spaces.id] }),
  folder: one(folders, {
    fields: [courses.folderId],
    references: [folders.id],
  }),
}))

export const cardImagesRelations = relations(cardImages, ({ one }) => ({
  card: one(cards, { fields: [cardImages.cardId], references: [cards.id] }),
}))

export const courseFavoritesRelations = relations(
  courseFavorites,
  ({ one }) => ({
    course: one(courses, {
      fields: [courseFavorites.courseId],
      references: [courses.id],
    }),
    user: one(user, {
      fields: [courseFavorites.userId],
      references: [user.id],
    }),
  })
)

export const courseCompletionsRelations = relations(
  courseCompletions,
  ({ one }) => ({
    course: one(courses, {
      fields: [courseCompletions.courseId],
      references: [courses.id],
    }),
    user: one(user, {
      fields: [courseCompletions.userId],
      references: [user.id],
    }),
  })
)

export const cardsRelations = relations(cards, ({ one }) => ({
  course: one(courses, {
    fields: [cards.courseId],
    references: [courses.id],
  }),
}))

export const courseEditorsRelations = relations(courseEditors, ({ one }) => ({
  course: one(courses, {
    fields: [courseEditors.courseId],
    references: [courses.id],
  }),
  user: one(user, { fields: [courseEditors.userId], references: [user.id] }),
}))
