import { relations } from "drizzle-orm"
import {
  boolean,
  date,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core"

/* -------------------------------------------------------------------------- */
/*  Auth — the shape better-auth expects. Generated by `@better-auth/cli`.     */
/* -------------------------------------------------------------------------- */

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  /** The public handle: what other learners see, so the email stays private. */
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
})

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
)

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    /** Hashed by better-auth (scrypt); never read by application code. */
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
)

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
)

/* -------------------------------------------------------------------------- */
/*  Lessons                                                                    */
/* -------------------------------------------------------------------------- */

export const courses = pgTable("courses", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: text("title").notNull(),
  /** Date of the lesson, distinct from `createdAt` (notes are typed up later). */
  date: date("date").notNull(),
  /**
   * The author. A course outlives its author's account only if we say so —
   * `set null` keeps the lesson readable, with no one able to edit it.
   */
  ownerId: text("owner_id").references(() => user.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
})

export const words = pgTable(
  "words",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    korean: text("korean").notNull(),
    romanization: text("romanization").notNull().default(""),
    translation: text("translation").notNull().default(""),
    note: text("note"),
    /** Rank in the lesson: the note's own order is meaningful. */
    position: integer("position").notNull(),
  },
  (table) => [index("words_course_idx").on(table.courseId, table.position)]
)

/** Write access granted by the owner. Read access needs no row: it is public. */
export const courseEditors = pgTable(
  "course_editors",
  {
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.courseId, table.userId] })]
)

/* -------------------------------------------------------------------------- */
/*  Progress — per learner, never shared                                       */
/* -------------------------------------------------------------------------- */

/**
 * How a learner stands on one word: `streak` counts the series answered right
 * in a row. `0` means the last answer was a miss — the word is due for review;
 * `KNOWN_STREAK` or more means acquired. A word never answered has no row.
 */
export const wordProgress = pgTable(
  "word_progress",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    wordId: uuid("word_id")
      .notNull()
      .references(() => words.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    streak: integer("streak").notNull().default(0),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.wordId] }),
    index("word_progress_course_idx").on(table.userId, table.courseId),
  ]
)

/** One series, complete or cut short. Free practice is never written here. */
export const runs = pgTable(
  "runs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    courseId: uuid("course_id")
      .notNull()
      .references(() => courses.id, { onDelete: "cascade" }),
    /** Cards the deck held — larger than the answers when it was cut short. */
    size: integer("size").notNull(),
    /** `false` when the learner closed the series before the last card. */
    completed: boolean("completed").notNull().default(true),
    /** The face that was shown first, kept so a recap can be read in context. */
    frontSide: text("front_side").notNull().default("korean"),
    finishedAt: timestamp("finished_at").defaultNow().notNull(),
  },
  (table) => [index("runs_course_idx").on(table.userId, table.courseId)]
)

/** One answered card of a series — what makes the recap possible. */
export const runWords = pgTable(
  "run_words",
  {
    runId: uuid("run_id")
      .notNull()
      .references(() => runs.id, { onDelete: "cascade" }),
    wordId: uuid("word_id")
      .notNull()
      .references(() => words.id, { onDelete: "cascade" }),
    /** `true` for "acquis", `false` for "à revoir". */
    known: boolean("known").notNull(),
    /** Rank in the deck, so the recap lists the words as they came up. */
    position: integer("position").notNull(),
  },
  (table) => [primaryKey({ columns: [table.runId, table.wordId] })]
)

/* -------------------------------------------------------------------------- */

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}))

export const coursesRelations = relations(courses, ({ many, one }) => ({
  words: many(words),
  editors: many(courseEditors),
  owner: one(user, { fields: [courses.ownerId], references: [user.id] }),
}))

export const wordsRelations = relations(words, ({ one }) => ({
  course: one(courses, {
    fields: [words.courseId],
    references: [courses.id],
  }),
}))

export const courseEditorsRelations = relations(courseEditors, ({ one }) => ({
  course: one(courses, {
    fields: [courseEditors.courseId],
    references: [courses.id],
  }),
  user: one(user, { fields: [courseEditors.userId], references: [user.id] }),
}))
